{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "eOtVDSMQAr5z"
   },
   "source": [
    "# **BASE**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: tabulate in c:\\users\\vishr\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (0.9.0)\n",
      "Requirement already satisfied: tk in c:\\users\\vishr\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (0.1.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install tabulate tk"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from operator import itemgetter\n",
    "from tabulate import tabulate\n",
    "import shutil\n",
    "from datetime import datetime, timedelta\n",
    "import os\n",
    "from collections import Counter\n",
    "import tkinter as tk\n",
    "from tkinter import messagebox"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "O0ftVu-te0oU",
    "outputId": "53550b6c-f136-4b41-f7eb-734dc6e7fcf0"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Task Management System Initialized!\n",
      "No tasks available.\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Placeholder for the tasks\n",
    "tasks = []\n",
    "# Archive list for completed tasks\n",
    "archived_tasks = []\n",
    "\n",
    "# List to store completed tasks history\n",
    "completed_tasks_history = []\n",
    "\n",
    "# Function to generate task analytics\n",
    "def generate_task_analytics():\n",
    "    total_tasks = len(tasks)\n",
    "    completed_tasks = sum(1 for task in tasks if task['status'] == 'Completed')\n",
    "    pending_tasks = total_tasks - completed_tasks\n",
    "\n",
    "    # Count tasks by priority\n",
    "    priority_count = Counter(task['priority'] for task in tasks)\n",
    "\n",
    "    # Count tasks by category\n",
    "    category_count = Counter(task['category'] for task in tasks)\n",
    "\n",
    "    # Display the analytics\n",
    "    print(\"\\n--- Task Analytics ---\")\n",
    "    print(f\"Total Tasks: {total_tasks}\")\n",
    "    print(f\"Completed Tasks: {completed_tasks} ({(completed_tasks / total_tasks) * 100:.2f}%)\")\n",
    "    print(f\"Pending Tasks: {pending_tasks} ({(pending_tasks / total_tasks) * 100:.2f}%)\")\n",
    "\n",
    "    print(\"\\nTasks by Priority:\")\n",
    "    for priority, count in priority_count.items():\n",
    "        print(f\"{priority}: {count} task(s)\")\n",
    "\n",
    "    print(\"\\nTasks by Category:\")\n",
    "    for category, count in category_count.items():\n",
    "        print(f\"{category}: {count} task(s)\")\n",
    "\n",
    "    print(\"\\n--- Upcoming Due Dates ---\")\n",
    "    # Sort tasks by due date\n",
    "    sorted_due_dates = sorted(tasks, key=lambda x: x['due_date'])\n",
    "    for task in sorted_due_dates:\n",
    "        print(f\"Task '{task['name']}' (Due: {task['due_date']})\")\n",
    "\n",
    "# Function to mark a task as completed and add it to the completed task history\n",
    "def mark_task_completed(index):\n",
    "    if index < 0 or index >= len(tasks):\n",
    "        print(\"Invalid task number.\")\n",
    "        return\n",
    "\n",
    "    task = tasks.pop(index)\n",
    "    task['status'] = 'Completed'\n",
    "    task['completed_on'] = datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")  # Add completion date\n",
    "    completed_tasks_history.append(task)\n",
    "    print(f\"Task '{task['name']}' has been marked as completed.\")\n",
    "\n",
    "# Function to view completed tasks history\n",
    "def view_completed_tasks_history():\n",
    "    if not completed_tasks_history:\n",
    "        print(\"No tasks have been completed yet.\")\n",
    "    else:\n",
    "        print(\"Completed Tasks History:\")\n",
    "        for i, task in enumerate(completed_tasks_history, start=1):\n",
    "            print(f\"{i}. Task: {task['name']}, Due Date: {task['due_date']}, Priority: {task['priority']}, Completed on: {task['completed_on']}\")\n",
    "\n",
    "# Function to set a reminder for a task\n",
    "def set_task_reminder(index, reminder_days_before):\n",
    "    if index < 0 or index >= len(tasks):\n",
    "        print(\"Invalid task number.\")\n",
    "        return\n",
    "\n",
    "    task = tasks[index]\n",
    "    due_date = datetime.strptime(task['due_date'], \"%Y-%m-%d\")\n",
    "    reminder_date = due_date - timedelta(days=reminder_days_before)\n",
    "\n",
    "    task['reminder'] = reminder_date.strftime(\"%Y-%m-%d\")\n",
    "    print(f\"Reminder set for task '{task['name']}' on {task['reminder']}.\")\n",
    "\n",
    "# Function to check and notify about tasks approaching their due date\n",
    "def check_due_dates():\n",
    "    today = datetime.now()\n",
    "    upcoming_tasks = []\n",
    "\n",
    "    for task in tasks:\n",
    "        due_date = datetime.strptime(task['due_date'], \"%Y-%m-%d\")\n",
    "        if due_date <= today + timedelta(days=1) and task.get('status') != 'Completed':\n",
    "            upcoming_tasks.append(task)\n",
    "\n",
    "    if upcoming_tasks:\n",
    "        print(\"Upcoming Tasks (Due within the next 24 hours):\")\n",
    "        for task in upcoming_tasks:\n",
    "            print(f\"Task: {task['name']}, Due Date: {task['due_date']}, Priority: {task['priority']}\")\n",
    "    else:\n",
    "        print(\"No tasks approaching their due date in the next 24 hours.\")\n",
    "\n",
    "# Function to archive completed tasks\n",
    "def archive_completed_tasks():\n",
    "    global archived_tasks\n",
    "    completed_tasks = [task for task in tasks if task.get('status') == 'Completed']\n",
    "    archived_tasks.extend(completed_tasks)\n",
    "    tasks[:] = [task for task in tasks if task.get('status') != 'Completed']\n",
    "    print(f\"{len(completed_tasks)} tasks archived.\")\n",
    "\n",
    "# Function to create a backup of the tasks file\n",
    "def backup_tasks_file():\n",
    "    if not os.path.exists('tasks.json'):\n",
    "        print(\"No tasks file found to backup.\")\n",
    "        return\n",
    "\n",
    "    timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "    backup_file_name = f\"tasks_backup_{timestamp}.json\"\n",
    "    shutil.copy('tasks.json', backup_file_name)\n",
    "    print(f\"Backup created: {backup_file_name}\")\n",
    "\n",
    "# Input validation for dates\n",
    "def is_valid_date(date_str):\n",
    "    try:\n",
    "        datetime.strptime(date_str, \"%Y-%m-%d\")\n",
    "        return True\n",
    "    except ValueError:\n",
    "        return False\n",
    "\n",
    "# Function to display the menu\n",
    "def display_menu():\n",
    "    print(\"\\nTask Management System\")\n",
    "    print(\"1. Add a Task\")\n",
    "    print(\"2. View All Tasks\")\n",
    "    print(\"3. Edit a Task\")\n",
    "    print(\"4. Delete a Task\")\n",
    "    print(\"5. Exit\")\n",
    "    print(\"6. Sort Tasks by Due Date\")\n",
    "    print(\"7. Sort Tasks by Priority\")\n",
    "    print(\"8. Filter Tasks by Category\")\n",
    "    print(\"9. Mark Task as Completed\")\n",
    "    print(\"10. Archive Completed Tasks\")\n",
    "    print(\"11. Check Due Dates (Reminder)\")\n",
    "    print(\"12. Set Task Reminder\")\n",
    "    print(\"13. View Completed Tasks History\")  # New option for viewing completed tasks\n",
    "    print(\"14. Generate Task Analytics\")  # New option for analytics\n",
    "    print(\"15. Exit\")\n",
    "\n",
    "# Updated add_task function with validation\n",
    "def add_task(task_name, due_date, priority, category):\n",
    "    if not task_name.strip():\n",
    "        print(\"Task name cannot be empty!\")\n",
    "        return\n",
    "    if not is_valid_date(due_date):\n",
    "        print(\"Invalid date format! Use YYYY-MM-DD.\")\n",
    "        return\n",
    "    if priority not in [\"High\", \"Medium\", \"Low\", 'high', 'medium', 'low']:\n",
    "        print(\"Invalid priority! Choose from High, Medium, or Low.\")\n",
    "        return\n",
    "\n",
    "    task = {\n",
    "        'name': task_name,\n",
    "        'due_date': due_date,\n",
    "        'priority': priority,\n",
    "        'category': category,\n",
    "        'status': 'Pending',  # default status\n",
    "    }\n",
    "    tasks.append(task)\n",
    "    print(f\"Task '{task_name}' added successfully!\")\n",
    "\n",
    "# Function to view tasks including their completion status\n",
    "def view_tasks():\n",
    "    if not tasks:\n",
    "        print(\"No tasks available.\")\n",
    "    else:\n",
    "        headers = [\"#\", \"Task Name\", \"Due Date\", \"Priority\", \"Category\", \"Status\"]\n",
    "        table = [[i + 1, task['name'], task['due_date'], task['priority'], task['category'], task.get('status', 'Incomplete')] for i, task in enumerate(tasks)]\n",
    "        print(tabulate(table, headers=headers, tablefmt=\"grid\"))\n",
    "\n",
    "\n",
    "\n",
    "# Function to edit a task\n",
    "def edit_task(index, new_name, new_due_date, new_priority, new_category):\n",
    "    if 0 <= index < len(tasks):\n",
    "        tasks[index]['name'] = new_name\n",
    "        tasks[index]['due_date'] = new_due_date\n",
    "        tasks[index]['priority'] = new_priority\n",
    "        tasks[index]['category'] = new_category\n",
    "        print(f\"Task {index + 1} updated successfully!\")\n",
    "    else:\n",
    "        print(\"Invalid task index!\")\n",
    "\n",
    "# Function to delete a task\n",
    "def delete_task(index):\n",
    "    if 0 <= index < len(tasks):\n",
    "        removed_task = tasks.pop(index)\n",
    "        print(f\"Task '{removed_task['name']}' deleted successfully!\")\n",
    "    else:\n",
    "        print(\"Invalid task index!\")\n",
    "\n",
    "# Update sorting and filtering functions to use tabulate\n",
    "def sort_tasks(by):\n",
    "    if not tasks:\n",
    "        print(\"No tasks to sort.\")\n",
    "        return\n",
    "    if by == \"due_date\":\n",
    "        sorted_tasks = sorted(tasks, key=itemgetter('due_date'))\n",
    "    elif by == \"priority\":\n",
    "        priority_order = {\"High\": 1, \"Medium\": 2, \"Low\": 3}\n",
    "        sorted_tasks = sorted(tasks, key=lambda x: priority_order.get(x['priority'], 4))\n",
    "    else:\n",
    "        print(\"Invalid sorting option!\")\n",
    "        return\n",
    "\n",
    "    headers = [\"#\", \"Task Name\", \"Due Date\", \"Priority\", \"Category\"]\n",
    "    table = [[i + 1, task['name'], task['due_date'], task['priority'], task['category']] for i, task in enumerate(sorted_tasks)]\n",
    "    print(tabulate(table, headers=headers, tablefmt=\"grid\"))\n",
    "\n",
    "def filter_tasks_by_category(category):\n",
    "    filtered_tasks = [task for task in tasks if task['category'].lower() == category.lower()]\n",
    "    if not filtered_tasks:\n",
    "        print(f\"No tasks found under the category '{category}'.\")\n",
    "        return\n",
    "\n",
    "    headers = [\"#\", \"Task Name\", \"Due Date\", \"Priority\", \"Category\"]\n",
    "    table = [[i + 1, task['name'], task['due_date'], task['priority'], task['category']] for i, task in enumerate(filtered_tasks)]\n",
    "    print(tabulate(table, headers=headers, tablefmt=\"grid\"))\n",
    "\n",
    "# Testing the setup\n",
    "print(\"Task Management System Initialized!\")\n",
    "view_tasks()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "kr4yi2nwfj1A",
    "outputId": "4fa736b0-92e7-46a4-dc7b-6e308cc2d19a"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tasks loaded successfully!\n",
      "\n",
      "Task Management System\n",
      "1. Add a Task\n",
      "2. View All Tasks\n",
      "3. Edit a Task\n",
      "4. Delete a Task\n",
      "5. Exit\n",
      "6. Sort Tasks by Due Date\n",
      "7. Sort Tasks by Priority\n",
      "8. Filter Tasks by Category\n",
      "9. Mark Task as Completed\n",
      "10. Archive Completed Tasks\n",
      "11. Check Due Dates (Reminder)\n",
      "12. Set Task Reminder\n",
      "13. View Completed Tasks History\n",
      "14. Generate Task Analytics\n",
      "15. Exit\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exiting Task Management System. Goodbye!\n",
      "Tasks saved successfully!\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "\n",
    "# Function to save tasks to a file\n",
    "def save_tasks_to_file(filename=\"tasks.json\"):\n",
    "    try:\n",
    "        with open(filename, \"w\") as file:\n",
    "            json.dump(tasks, file, indent=4)\n",
    "        print(\"Tasks saved successfully!\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error saving tasks: {e}\")\n",
    "\n",
    "# Function to load tasks from a file\n",
    "def load_tasks_from_file(filename=\"tasks.json\"):\n",
    "    global tasks\n",
    "    try:\n",
    "        with open(filename, \"r\") as file:\n",
    "            tasks = json.load(file)\n",
    "        print(\"Tasks loaded successfully!\")\n",
    "    except FileNotFoundError:\n",
    "        print(\"No saved tasks found. Starting fresh.\")\n",
    "        tasks = []\n",
    "    except Exception as e:\n",
    "        print(f\"Error loading tasks: {e}\")\n",
    "\n",
    "# Integrating history feature into task manager\n",
    "def task_manager():\n",
    "    load_tasks_from_file()\n",
    "\n",
    "    while True:\n",
    "        display_menu()\n",
    "        choice = input(\"Enter your choice (1-15): \")\n",
    "\n",
    "        if choice == '1':\n",
    "            # Add a Task\n",
    "            task_name = input(\"Enter the task name: \")\n",
    "            due_date = input(\"Enter the due date (YYYY-MM-DD): \")\n",
    "            priority = input(\"Enter the priority (High/Medium/Low): \")\n",
    "            category = input(\"Enter the category (e.g., Work/Personal/Urgent): \")\n",
    "            add_task(task_name, due_date, priority, category)\n",
    "            save_tasks_to_file()\n",
    "\n",
    "        elif choice == '2':\n",
    "            # View All Tasks\n",
    "            view_tasks()\n",
    "\n",
    "        elif choice == '3':\n",
    "            # Edit a Task\n",
    "            view_tasks()\n",
    "            try:\n",
    "                index = int(input(\"Enter the task number to edit: \")) - 1\n",
    "                new_name = input(\"Enter the new task name: \")\n",
    "                new_due_date = input(\"Enter the new due date (YYYY-MM-DD): \")\n",
    "                new_priority = input(\"Enter the new priority (High/Medium/Low): \")\n",
    "                new_category = input(\"Enter the new category (e.g., Work/Personal/Urgent): \")\n",
    "                edit_task(index, new_name, new_due_date, new_priority, new_category)\n",
    "                save_tasks_to_file()\n",
    "            except ValueError:\n",
    "                print(\"Invalid input! Please enter a number for the task index.\")\n",
    "\n",
    "        elif choice == '4':\n",
    "            # Delete a Task\n",
    "            view_tasks()\n",
    "            try:\n",
    "                index = int(input(\"Enter the task number to delete: \")) - 1\n",
    "                delete_task(index)\n",
    "                save_tasks_to_file()\n",
    "            except ValueError:\n",
    "                print(\"Invalid input! Please enter a number for the task index.\")\n",
    "\n",
    "        elif choice == '6':\n",
    "            # Sort Tasks by Due Date\n",
    "            sort_tasks(\"due_date\")\n",
    "\n",
    "        elif choice == '7':\n",
    "            # Sort Tasks by Priority\n",
    "            sort_tasks(\"priority\")\n",
    "\n",
    "        elif choice == '8':\n",
    "            # Filter Tasks by Category\n",
    "            category = input(\"Enter the category to filter by: \")\n",
    "            filter_tasks_by_category(category)\n",
    "\n",
    "        elif choice == '9':\n",
    "            # Mark Task as Completed\n",
    "            view_tasks()\n",
    "            try:\n",
    "                index = int(input(\"Enter the task number to mark as completed: \")) - 1\n",
    "                mark_task_completed(index)\n",
    "                save_tasks_to_file()\n",
    "            except ValueError:\n",
    "                print(\"Invalid input! Please enter a number for the task index.\")\n",
    "\n",
    "        elif choice == '10':\n",
    "            # Archive Completed Tasks\n",
    "            archive_completed_tasks()\n",
    "\n",
    "        elif choice == '11':\n",
    "            # Check Due Dates\n",
    "            check_due_dates()\n",
    "\n",
    "        elif choice == '12':\n",
    "            # Set Task Reminder\n",
    "            view_tasks()\n",
    "            try:\n",
    "                index = int(input(\"Enter the task number to set a reminder: \")) - 1\n",
    "                reminder_days_before = int(input(\"Enter the number of days before the due date to set the reminder: \"))\n",
    "                set_task_reminder(index, reminder_days_before)\n",
    "                save_tasks_to_file()\n",
    "            except ValueError:\n",
    "                print(\"Invalid input! Please enter a number for the task index or reminder days.\")\n",
    "\n",
    "        elif choice == '13':\n",
    "            # View Completed Tasks History\n",
    "            view_completed_tasks_history()\n",
    "\n",
    "        elif choice == '14':\n",
    "            # Generate Task Analytics\n",
    "            generate_task_analytics()\n",
    "\n",
    "        elif choice == '15':\n",
    "            # Exit\n",
    "            print(\"Exiting Task Management System. Goodbye!\")\n",
    "            save_tasks_to_file()\n",
    "            break\n",
    "        else:\n",
    "            print(\"Invalid choice! Please enter a number between 1 and 15.\")\n",
    "\n",
    "\n",
    "# Start the updated task manager\n",
    "task_manager()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "zwUOOH8gAvnR"
   },
   "source": [
    "# **GUI**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import simpledialog, messagebox\n",
    "\n",
    "# Create the main window\n",
    "root = tk.Tk()\n",
    "root.title(\"Task Management System\")\n",
    "root.geometry(\"500x600\")  # Adjust the window size to fit all buttons\n",
    "\n",
    "# Placeholder task list\n",
    "tasks = []\n",
    "\n",
    "# Function that will be called when each button is clicked\n",
    "def button_click(option):\n",
    "    if option == 1:  # Add a Task\n",
    "        add_task()\n",
    "    elif option == 2:  # View All Tasks\n",
    "        view_all_tasks()\n",
    "    elif option == 3:  # Edit a Task\n",
    "        edit_task()\n",
    "    elif option == 4:  # Delete a Task\n",
    "        delete_task()\n",
    "    elif option == 5:  # Exit\n",
    "        root.quit()\n",
    "    elif option == 6:  # Sort Tasks by Due Date\n",
    "        sort_tasks_by_due_date()\n",
    "    elif option == 7:  # Sort Tasks by Priority\n",
    "        sort_tasks_by_priority()\n",
    "    elif option == 8:  # Filter Tasks by Category\n",
    "        filter_tasks_by_category()\n",
    "    elif option == 9:  # Mark Task as Completed\n",
    "        mark_task_completed()\n",
    "    elif option == 10:  # Archive Completed Tasks\n",
    "        archive_completed_tasks()\n",
    "    elif option == 11:  # Check Due Dates (Reminder)\n",
    "        check_due_dates()\n",
    "    elif option == 12:  # Set Task Reminder\n",
    "        set_task_reminder()\n",
    "    elif option == 13:  # View Completed Tasks History\n",
    "        view_completed_tasks_history()\n",
    "    elif option == 14:  # Generate Task Analytics\n",
    "        generate_task_analytics()\n",
    "    elif option == 15:  # Exit\n",
    "        root.quit()\n",
    "\n",
    "# Function to add a task\n",
    "def add_task():\n",
    "    task_name = simpledialog.askstring(\"Input\", \"Enter task name:\")\n",
    "    due_date = simpledialog.askstring(\"Input\", \"Enter due date (YYYY-MM-DD):\")\n",
    "    priority = simpledialog.askstring(\"Input\", \"Enter priority (High/Medium/Low):\")\n",
    "    category = simpledialog.askstring(\"Input\", \"Enter category:\")\n",
    "    task = {\"name\": task_name, \"due_date\": due_date, \"priority\": priority, \"category\": category, \"completed\": False}\n",
    "    tasks.append(task)\n",
    "    messagebox.showinfo(\"Task Added\", f\"Task '{task_name}' added successfully.\")\n",
    "\n",
    "# Function to view all tasks\n",
    "def view_all_tasks():\n",
    "    all_tasks = \"\\n\".join([f\"{task['name']} - Due: {task['due_date']} - Priority: {task['priority']} - Category: {task['category']}\" for task in tasks])\n",
    "    messagebox.showinfo(\"All Tasks\", all_tasks if all_tasks else \"No tasks available.\")\n",
    "\n",
    "# Function to edit a task\n",
    "def edit_task():\n",
    "    task_name = simpledialog.askstring(\"Input\", \"Enter the name of the task to edit:\")\n",
    "    for task in tasks:\n",
    "        if task['name'] == task_name:\n",
    "            new_name = simpledialog.askstring(\"Edit\", f\"Enter new name for task '{task_name}':\")\n",
    "            new_due_date = simpledialog.askstring(\"Edit\", \"Enter new due date (YYYY-MM-DD):\")\n",
    "            new_priority = simpledialog.askstring(\"Edit\", \"Enter new priority (High/Medium/Low):\")\n",
    "            new_category = simpledialog.askstring(\"Edit\", \"Enter new category:\")\n",
    "            task.update({\"name\": new_name, \"due_date\": new_due_date, \"priority\": new_priority, \"category\": new_category})\n",
    "            messagebox.showinfo(\"Task Edited\", f\"Task '{task_name}' updated successfully.\")\n",
    "            return\n",
    "    messagebox.showerror(\"Task Not Found\", f\"Task '{task_name}' not found.\")\n",
    "\n",
    "# Function to delete a task\n",
    "def delete_task():\n",
    "    task_name = simpledialog.askstring(\"Input\", \"Enter the name of the task to delete:\")\n",
    "    for task in tasks:\n",
    "        if task['name'] == task_name:\n",
    "            tasks.remove(task)\n",
    "            messagebox.showinfo(\"Task Deleted\", f\"Task '{task_name}' deleted successfully.\")\n",
    "            return\n",
    "    messagebox.showerror(\"Task Not Found\", f\"Task '{task_name}' not found.\")\n",
    "\n",
    "# Function to sort tasks by due date\n",
    "def sort_tasks_by_due_date():\n",
    "    tasks.sort(key=lambda x: x['due_date'])\n",
    "    messagebox.showinfo(\"Tasks Sorted\", \"Tasks sorted by due date.\")\n",
    "\n",
    "# Function to sort tasks by priority\n",
    "def sort_tasks_by_priority():\n",
    "    priority_order = {\"High\": 1, \"Medium\": 2, \"Low\": 3}\n",
    "    tasks.sort(key=lambda x: priority_order.get(x['priority'], 3))\n",
    "    messagebox.showinfo(\"Tasks Sorted\", \"Tasks sorted by priority.\")\n",
    "\n",
    "# Function to filter tasks by category\n",
    "def filter_tasks_by_category():\n",
    "    category = simpledialog.askstring(\"Input\", \"Enter category to filter by:\")\n",
    "    filtered_tasks = [task for task in tasks if task['category'] == category]\n",
    "    filtered_tasks_str = \"\\n\".join([f\"{task['name']} - Due: {task['due_date']} - Priority: {task['priority']}\" for task in filtered_tasks])\n",
    "    messagebox.showinfo(\"Filtered Tasks\", filtered_tasks_str if filtered_tasks_str else \"No tasks found in this category.\")\n",
    "\n",
    "# Function to mark a task as completed\n",
    "def mark_task_completed():\n",
    "    task_name = simpledialog.askstring(\"Input\", \"Enter the name of the task to mark as completed:\")\n",
    "    for task in tasks:\n",
    "        if task['name'] == task_name:\n",
    "            task['completed'] = True\n",
    "            messagebox.showinfo(\"Task Completed\", f\"Task '{task_name}' marked as completed.\")\n",
    "            return\n",
    "    messagebox.showerror(\"Task Not Found\", f\"Task '{task_name}' not found.\")\n",
    "\n",
    "# Function to archive completed tasks\n",
    "def archive_completed_tasks():\n",
    "    global tasks\n",
    "    tasks = [task for task in tasks if not task['completed']]\n",
    "    messagebox.showinfo(\"Archived Tasks\", \"Completed tasks archived successfully.\")\n",
    "\n",
    "# Function to check due dates (reminder)\n",
    "def check_due_dates():\n",
    "    today = \"2024-12-25\"  # Example: Get today's date (can use datetime module in real use case)\n",
    "    due_tasks = [task for task in tasks if task['due_date'] == today]\n",
    "    due_tasks_str = \"\\n\".join([f\"{task['name']} - Due: {task['due_date']}\" for task in due_tasks])\n",
    "    messagebox.showinfo(\"Due Tasks\", due_tasks_str if due_tasks_str else \"No tasks due today.\")\n",
    "\n",
    "# Function to set a task reminder\n",
    "def set_task_reminder():\n",
    "    task_name = simpledialog.askstring(\"Input\", \"Enter the task name to set reminder for:\")\n",
    "    reminder_time = simpledialog.askstring(\"Input\", \"Enter reminder time (HH:MM):\")\n",
    "    # You can implement reminder functionality here (e.g., send notification at the specified time)\n",
    "    messagebox.showinfo(\"Reminder Set\", f\"Reminder for task '{task_name}' set at {reminder_time}.\")\n",
    "\n",
    "# Function to view completed tasks history\n",
    "def view_completed_tasks_history():\n",
    "    completed_tasks = [task for task in tasks if task['completed']]\n",
    "    completed_tasks_str = \"\\n\".join([f\"{task['name']} - Completed on {task['due_date']}\" for task in completed_tasks])\n",
    "    messagebox.showinfo(\"Completed Tasks\", completed_tasks_str if completed_tasks_str else \"No completed tasks.\")\n",
    "\n",
    "# Function to generate task analytics\n",
    "def generate_task_analytics():\n",
    "    total_tasks = len(tasks)\n",
    "    completed_tasks = len([task for task in tasks if task['completed']])\n",
    "    pending_tasks = total_tasks - completed_tasks\n",
    "    messagebox.showinfo(\"Task Analytics\", f\"Total Tasks: {total_tasks}\\nCompleted Tasks: {completed_tasks}\\nPending Tasks: {pending_tasks}\")\n",
    "\n",
    "# Create buttons for all 15 options\n",
    "options = [\n",
    "    \"Add a Task\", \"View All Tasks\", \"Edit a Task\", \"Delete a Task\", \"Exit\",\n",
    "    \"Sort Tasks by Due Date\", \"Sort Tasks by Priority\", \"Filter Tasks by Category\",\n",
    "    \"Mark Task as Completed\", \"Archive Completed Tasks\", \"Check Due Dates (Reminder)\",\n",
    "    \"Set Task Reminder\", \"View Completed Tasks History\", \"Generate Task Analytics\", \"Exit\"\n",
    "]\n",
    "\n",
    "# Create buttons dynamically based on the options list\n",
    "for i, option in enumerate(options, start=1):\n",
    "    button = tk.Button(root, text=option, width=20, command=lambda i=i: button_click(i))\n",
    "    button.grid(row=i, column=0, pady=5)\n",
    "\n",
    "# Run the application\n",
    "root.mainloop()\n"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "collapsed_sections": [
    "eOtVDSMQAr5z"
   ],
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
